- Gemfile
- Gemfile.lock
- config/unicorn.rb
ユニコーンのgem導入、configにユニコーンの設定用ファイル作成
本番環境でユニコーンを使用して動作させる為
> ユニコーンの導入と設定

- app/controllers/hello_controller.rb
- app/views/hello/index.html.haml
- config/routes.rb
- config/unicorn.rb
- test/controllers/hello_controller_test.rb
・デプロイ時にhello worldを表示させるページのみ作成
・Nginxを介した処理を行うためにunicornの設定を修正
Nginxを介した処理を行うためにunicornの設定を修正
> 初回デプロイ続きの続き

- app/controllers/application_controller.rb
- config/deploy.rb
- config/deploy/production.rb
Basic認証の設定
本番環境を閲覧するのにパスワードを設定する為
> Basic認証の設定

- app/assets/stylesheets/modules/_buy-show.scss
- app/controllers/buys_controller.rb
- app/views/buys/show.html.haml
- config/routes.rb
商品購入ページのマークアップ
商品購入ページを表示する為
画像
https://gyazo.com/acdbc63b1c7bb23a8ffd5217414edd23
https://gyazo.com/b711095ce4d24a9d0c52f5ae4948c8e3
> #31 buys#showアクションを追加

- Gemfile
- Gemfile.lock
- seed-fu導入
- ancestry導入
- データ作成のため
- 多階層カテゴリ実装のため
> #39 必要なGemを導入

- app/models/brand.rb
- app/models/category.rb
- app/models/delivery_day.rb
- app/models/delivery_way.rb
- app/models/size.rb
- db/migrate/20190831030417_create_categories.rb
- db/migrate/20190831031313_create_brands.rb
- db/migrate/20190831031639_create_delivery_ways.rb
- db/migrate/20190831031746_create_delivery_days.rb
- db/migrate/20190831031841_create_sizes.rb
- db/schema.rb
- test/fixtures/brands.yml
- test/fixtures/categories.yml
- test/fixtures/delivery_days.yml
- test/fixtures/delivery_ways.yml
- test/fixtures/sizes.yml
- test/models/brand_test.rb
- test/models/category_test.rb
- test/models/delivery_day_test.rb
- test/models/delivery_way_test.rb
- test/models/size_test.rb
- 下記のモデルを作成
- category カテゴリー
- brand ブランド
- delivery_way 配送方法
- delivery_day 発送までの日数
- size サイズ
- 必須機能作成のため
- アソシエーション等は記載していません(本当にテーブル作成しただけ)
- 機能実装の際に各自記載をお願いします。
> #41 #44 各種テーブル作成

- app/models/brand.rb
- app/models/category.rb
- app/models/condition.rb
- app/models/delivery_day.rb
- app/models/delivery_way.rb
- app/models/item.rb
- app/models/size.rb
- db/migrate/20190831044618_add_category_to_items.rb
- db/schema.rb
Itemモデルと関連付けモデルたちのアソシエーションを定義
モデル間の関係性を定義する為
> WIP Itemモデルと関連付けモデルたちのアソシエーションを定義

- app/assets/stylesheets/modules/_footer.scss
- app/assets/stylesheets/modules/_header.scss
- app/assets/stylesheets/modules/_index.scss
- トップページ関連のcss整理
- カテゴリ機能実装にあたり、css修正の必要があるため
- 機能実装に関係のない修正のコミットを分けるため、先に実施
> #54 cssリファクタリング

- app/assets/javascripts/application.js
- jQuery読み込みの記述を追加
- jQueryを使えるようにするため
> jQuery読み込み

- app/assets/stylesheets/modules/_new_users_info.scss
- app/controllers/hello_controller.rb
- app/views/hello/step6.html.haml
- config/routes.rb
- db/schema.rb
What
本人情報登録ページのマークアップ
Why
本人情報を登録するため
> 本人情報登録ページのマークアップ

- config/initializers/carrierwave.rb
本番環境でのみAWSキーを取得するように変更
環境変数を設定していないローカル環境でAWSキーを取得できないエラーが発生していた為
> 本番環境でのみAWSキーを取得するように変更

- app/assets/stylesheets/modules/_index.scss
- app/assets/stylesheets/modules/_item-link-card.scss
- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/index.html.haml
- app/views/share/_item-link-card.html.haml
- トップページに、DBから引っ張って来た商品を一覧で表示する
- 規定のカテゴリー・ブランドごとに、最新の商品から表示
- 商品をトップページに表示させるため
- 商品詳細ページが完成次第、詳細ページへのリンクを追加する
Close #65
> #65 商品一覧表示

- app/assets/stylesheets/modules/_footer.scss
- app/assets/stylesheets/modules/_header.scss
- app/assets/stylesheets/modules/_index.scss
- app/assets/stylesheets/modules/_item-link-card.scss
- トップページ、商品一覧関連のcss整理
- 可読性及び保守性向上のため
> #54 cssリファクタリング2

- app/assets/stylesheets/modules/_buy-show.scss
- app/assets/stylesheets/modules/_item-show.scss
- app/assets/stylesheets/modules/_sign-up.scss
- app/assets/stylesheets/modules/_simple-footer.scss
- app/assets/stylesheets/modules/_simple-header.scss
- 商品詳細関連のcss整理
- 可読性及び保守性向上のため
> #54 cssリファクタリング3

- app/assets/stylesheets/modules/_pankuzu.scss
- app/views/categories/show.html.haml
- app/views/share/_breadcrumbs.html.haml
- パンくずリストの表示位置修正
- 見た目を綺麗にするため
[![Screenshot from Gyazo](https://gyazo.com/620d5926e5eb31d4d865616f7ca21b5c/raw)](https://gyazo.com/620d5926e5eb31d4d865616f7ca21b5c)
> #58 パンくずリストの見た目調整

- Gemfile
- Gemfile.lock
- kaminari導入
- ページネーションで使用するため
> #103 kaminari導入

- Gemfile
- Gemfile.lock
> Revert "#103 kaminari導入"

- app/assets/stylesheets/card.scss
- app/assets/stylesheets/config/_variable.scss
- app/assets/stylesheets/modules/_card-show.scss
- app/assets/stylesheets/modules/_category.scss
- app/assets/stylesheets/modules/_delete_account.scss
- app/assets/stylesheets/modules/_header.scss
- app/assets/stylesheets/modules/_item-link-card.scss
- app/assets/stylesheets/modules/_item-show.scss
- app/assets/stylesheets/modules/_mypage-right-footer.scss
- app/assets/stylesheets/modules/_new-users-info.scss
- app/assets/stylesheets/modules/_purchase-show.scss
- app/assets/stylesheets/modules/_sign-in.scss
- app/assets/stylesheets/modules/_simple-header.scss
- app/assets/stylesheets/modules/_step1.scss
- app/assets/stylesheets/modules/_step2.scss
- app/assets/stylesheets/modules/_step3.scss
- app/assets/stylesheets/modules/_step4.scss
- app/assets/stylesheets/modules/_step5.scss
- app/assets/stylesheets/modules/_users.scss
> #54 cssリファクタリング4

- Gemfile
- Gemfile.lock
- rails-controller-testing導入
- コントローラーのテストのため
> #103 rails-controller-testing導入

- Gemfile
- Gemfile.lock
- app/models/item.rb
- app/models/user.rb
- spec/factories/brand.rb
- spec/factories/category.rb
- spec/factories/condition.rb
- spec/factories/delivery_day.rb
- spec/factories/delivery_way.rb
- spec/factories/item.rb
- spec/factories/postage.rb
- spec/factories/region.rb
- spec/factories/size.rb
- spec/factories/user.rb
- spec/models/item_spec.rb
- spec/rails_helper.rb
> Itemモデルのテスト

- app/assets/stylesheets/mixin/_mixin.scss
- app/assets/stylesheets/modules/_footer.scss
- app/assets/stylesheets/modules/_header.scss
- app/assets/stylesheets/modules/_index.scss
- app/assets/stylesheets/modules/_item-show.scss
- app/assets/stylesheets/modules/_item_new.scss
- app/assets/stylesheets/modules/_mypage-right-body.scss
- app/assets/stylesheets/modules/_step1.scss
- app/assets/stylesheets/modules/_step4.scss
- app/views/items/show.html.haml
- app/views/share/_item-link-card.html.haml
- app/views/share/_simple-header.html.haml
- app/views/shared/_main_footer.html.haml
- app/views/shared/_main_header.html.haml
> #54 リファクタリング5
